sudo: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - cd web && npm install

script:
  - cd web && npm run test

after_success:
  - cd web && npm run codecov
